// Auto-generated by icon-pipeline
// DO NOT EDIT MANUALLY

export const icons = {
  caution: require('./caution.png'),
  cloud: require('./cloud.png'),
  construction: require('./construction.png'),
  incident: require('./incident.png'),
  information: require('./information.png'),
  roadblock: require('./roadblock.png'),
  route: require('./route.png'),
  truck: require('./truck.png'),
  weather_station: require('./weather_station.png'),
  work_zone: require('./work_zone.png'),
} as const;

export type IconName = keyof typeof icons;
